### ISSUE TITLE
Auditd only allows up to 64 fields

### ISSUE THREAD

**Issue by sqall01** [izysec/linux-audit#1]
Hi,

I read your medium articles about auditd (https://izyknows.medium.com/linux-auditd-for-threat-detection-d06c8b941505) and started playing around with it (thanks for the article). I wanted to disable all message types to only allow ones that I specifically allow and used your `exclude-records.rules` as starting point.

However, it did not work. After debugging I found this in the man page of auditctl for the `-F` paramater (Ubuntu 22.04): `You may have up to 64 fields passed on a single command line.`

Furthermore, the man page for `-F` says `Each field equation is anded with each other to trigger an audit record.`. Meaning this one liner would actually not work at all, since you need an OR operation for what want to do. Since I am still playing around, if I find a efficient solution for this I let you know.

**Comment by izysec** [comment]
Hi @sqall01  -- that's a great find, thank you! I need to get back and do some testing myself it seems. After which I'll make changes to the repo and the article. I look forward to your findings as well and hope you don't mind me giving you credit :)
Thanks again!

**Comment by izysec** [comment]
Hi @sqall01. I had a deeper look into it and did some testing, you're entirely right. I've removed the file from GitHub and added some clarity to [the blog](https://izyknows.medium.com/linux-auditd-for-threat-detection-d06c8b941505).

> Each line in the auditd rule file gets evaluated sequentially and while compounding rules are generally a good idea from a performance perspective, unfortunately you cannot do that with the above exclusions. So for each msgtype you’d like to exclude, you’d need to have it as a separate line. 
> 
> As for syscalls, the auditd engine intercepts each syscall that a program makes, attempting to match it against system call rules. These rules, when sent to the kernel, the syscall fields are all put into a mask so that one compare can determine if the syscall matches or not. So in that case, combining syscalls in one rule is efficient.

Thanks again for the feedback!
